### ISSUE TITLE
constants/secrets.dart file doesn't exists

### ISSUE THREAD

**Issue by Labib-Ahmed-1604065** [nixrajput/video-calling-app-flutter#3]
I tried to run the code by myself, but **channel_controller.dart** file requires **secrets.dart** file. Please add the file.

**Comment by nixrajput** [comment]
1. Make `secrets.dart` file in constants folder.
2. Then add below code to the file.
3. Provide your Agora ID and Certificate.

``` dart
abstract class AppSecrets {
  static const appId = "YOUR_APP_ID";
  static const certificate = "YOUR _APP_CERTIFICATE";
}
```

**Comment by Labib-Ahmed-1604065** [comment]
Thanks a lot.
